<?xml version="1.0" encoding="utf-8"?>
<Project Sdk="Microsoft.NET.Sdk.BlazorWebAssembly">
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <LangVersion>default</LangVersion>
    <BlazorWebAssemblyEnableLinking>false</BlazorWebAssemblyEnableLinking>
    <RootNamespace>LoreBuilder</RootNamespace>
    <ServiceWorkerAssetsManifest>service-worker-assets.js</ServiceWorkerAssetsManifest>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Bolero" Version="0.25.63" />
    <PackageReference Include="Bolero.Build" Version="0.25.63" />
    <PackageReference Include="Microsoft.AspNetCore.Components.WebAssembly.DevServer" Version="8.0.30" />
    <PackageReference Include="System.Net.Http.Json" Version="8.0.1" />
    <PackageReference Include="Blazored.LocalStorage" Version="4.5.0" />
    <PackageReference Include="Radzen.Blazor" Version="7.1.2" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\..\external\blazor-dragdrop\Plk.Blazor.DragDrop\Plk.Blazor.DragDrop.csproj" />
    <ProjectReference Include="..\FunSharp.Common\FunSharp.Common.fsproj" />
    <ProjectReference Include="..\FunSharp.Components\FunSharp.Components.fsproj" />
  </ItemGroup>
  <ItemGroup>
    <ServiceWorker Include="wwwroot\service-worker.js" PublishedContent="wwwroot\service-worker.published.js" />
  </ItemGroup>
  <ItemGroup>
    <Content Update="wwwroot\assets\symbols\white\axe.svg">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Update="wwwroot\assets\symbols\black\axe.svg">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
  </ItemGroup>
  <ItemGroup>
    <Compile Include="Routes.fs" />
    <Compile Include="Model\Common.fs" />
    <Compile Include="Model\Card.fs" />
    <Compile Include="Model\Cluster.fs" />
    <Compile Include="Model\CanvasState.fs" />
    <Compile Include="Model\CanvasTree.fs" />
    <Compile Include="Model\HoverTest.fs" />
    <Compile Include="Model\Application.fs" />
    <Compile Include="Builders.fs" />
    <Compile Include="CardData.fs" />
    <Compile Include="Utils.fs" />
    <Compile Include="Components\CardBadge.fs" />
    <None Include="Components\CardBadge.bolero.css" />
    <Compile Include="Components\HiddenCard.fs" />
    <None Include="Components\HiddenCard.bolero.css" />
    <Compile Include="Components\Card.fs" />
    <None Include="Components\Card.bolero.css" />
    <Compile Include="Components\CardStack.fs" />
    <None Include="Components\CardStack.bolero.css" />
    <Compile Include="Components\LoreCluster.fs" />
    <None Include="Components\LoreCluster.bolero.css" />
    <Compile Include="Components\Canvas.fs" />
    <None Include="Components\Canvas.bolero.css" />
    <Compile Include="Components\PageNav.fs" />
    <Compile Include="Pages\NotFound.fs" />
    <Compile Include="Pages\HoverTest.fs" />
    <Compile Include="Pages\CardTest.fs" />
    <Compile Include="Pages\DragDropTest.fs" />
    <Compile Include="Pages\StackTest.fs" />
    <Compile Include="Pages\LoreClusterTest.fs" />
    <Compile Include="Pages\LoreWeb.fs" />
    <Compile Include="Pages\CardGallery.fs" />
    <Compile Include="Pages\Home.fs" />
    <Compile Include="Update.fs" />
    <Compile Include="Main.fs" />
    <None Include="LoreBuilder.bolero.css" />
    <Compile Include="Startup.fs" />
  </ItemGroup>
</Project>
